- name: Check Oracle database open mode
  ansible.builtin.shell: |
    docker exec {{ oracle_container_name }} bash -lc "echo \"SET HEADING OFF FEEDBACK OFF; SELECT open_mode FROM v\\$database;\" | sqlplus -s / as sysdba"
  register: oracle_mode
  changed_when: false

- name: Assert Oracle is OPEN or RESETLOGS
  ansible.builtin.assert:
    that:
      - oracle_mode.stdout is search('READ WRITE|RESETLOGS')

- name: Optional: query sample table (if present)
  ansible.builtin.shell: |
    docker exec {{ oracle_container_name }} bash -lc "echo \"SET HEADING OFF FEEDBACK OFF; SELECT COUNT(*) FROM app.t;\" | sqlplus -s / as sysdba"
  register: oracle_demo_cnt
  failed_when: false
  changed_when: false

- debug:
    var: oracle_demo_cnt.stdout