- name: Ensure SQL Server backups host directory exists
  ansible.builtin.file:
    path: "{{ sql_backups_host_dir }}"
    state: directory
    mode: "0755"

- name: Run SQL Server 2019 container
  community.docker.docker_container:
    name: "{{ mssql_container_name }}"
    image: "{{ mssql_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ mssql_port }}:1433"
    env:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "{{ sa_password }}"
      MSSQL_PID: "{{ mssql_pid }}"
    volumes:
      - "{{ sql_backups_host_dir }}:{{ mssql_backups_container_dir }}"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P \"$SA_PASSWORD\" -Q \"SELECT 1\" -b -o /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

- name: Wait for SQL Server port
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: "{{ mssql_port }}"
    delay: 5
    timeout: "{{ startup_wait_seconds }}"

---
# Sequência única: pré-check → restore → pós-check
- import_tasks: precheck.yml
- import_tasks: "{{ restore_type }}.yml"  # full.yml, full_diff.yml, pit.yml
- import_tasks: postcheck.yml